### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by amqndin** [Dhanush-777x/vimium-c-catppuccin#1]
![image](https://github.com/user-attachments/assets/c22d703f-9884-436b-b223-395bc719c4b0)
as you can see on the image font size is too small. and as for second issue you should add borders around the omnibar because i have catppuccin themeon every website so it doesnt overlap with each other, would be nice.

**Comment by dhanush777x** [comment]
This issue occurs in firefox but it works perfectly fine in brave. I have no idea why this happens. Kindly do let me know if you found the issue.

**Comment by amqndin** [comment]
> This issue occurs in firefox but it works perfectly fine in brave. I have no idea why this happens. Kindly do let me know if you found the issue.

it's probably because brave is on chromium and Firefox has it's own thing, and the extensions are little different. I ended up just  fixing it myself

**Comment by dhanush777x** [comment]
Can you create a pull request uploading your vimium-c css file for Firefox as a seperate file ?

**Comment by ParadoxPacer** [comment]
Does anybody have a fix for this yet? I have been having the same issue.

**Comment by vuja0** [comment]
I'm still getting the same error only on firefox based browsers. Is there mayby any fix available?

**Comment by ParadoxPacer** [comment]
You need to change every instance in vimium-c.css where the measurement `rem` is used and convert that to px (pixels) (https://nekocalc.com/px-to-rem-converter)


> I'm still getting the same error only on firefox based browsers. Is there mayby any fix available?

**Comment by amqndin** [comment]
> Can you create a pull request uploading your vimium-c css file for Firefox as a seperate file ?

ah, sorry i am only noticing this now. i dont know if i have the time for it, but if you're willing to here is what my css currently looks like. 

```css
/*
vimium cattpuccin-mocha blue theme

Adaped from css code by:
(c) 2020 Saïd Dermoumi
https://github.com/dermoumi/vimium-snow
*/

/* #ui */
/* ^ do not touch this line ^ */

/* .R,.DHM,.HM,.IHS,.IH,.BH,.MH {
    color: #c6d0f5;
    background: #181825;
} */

/* link hints */
.LH {
  border: 2px #89b4fa solid;
  background: #313244;
  margin-top: -2px;
  margin-left: -2px;
  color: #c6d0f5;
  z-index: 0;
  scale: 1.1;
  font-family: JetBrainsMono Nerd Font;
  box-shadow: 0px 2px 11px rgb(0, 0, 0, 0.12);
}

.LH:before {
  position: absolute;
  background: #313244;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  content: "";
  z-index: -1;
}

.D .LH {
  border-color: #89b4fa;
  color: #c6d0f5;
}

/* hints matching chars */
.MC {
  color: #89b4fa;
}

.D .MC {
  color: #89b4fa;
}

/* bottom hud */
.HUD {
  bottom: 1rem;
  left: unset;
  right: 1rem;
  border: 1px #89b4fa solid;
  border-radius: 6px;
  box-shadow: 0 3px 10px #232634;
  padding: 0.5rem 1rem;
  height: 1.5rem !important;
  line-height: 21px;
  text-transform: lowercase;
  background: #181825;
  color: #c6d0f5;
  max-width: 420px;
  min-width: unset;
  display: flex;
  align-items: center;
}

.has-dark .HUD {
  background: #181825;
}

.HUD.UI {
  min-width: 180px;
  align-items: unset;
}

.Omnibar {
  padding-bottom: 20px;
}

.HUD:after {
  border: none;
  background: #181825;
}

.HUD.D:after {
  background: #181825;
}

/* #omni */
/* ^ do not touch this line ^ */

* {
  font-family: "JetBrainsMono Nerd Font" !important;
}

.transparent {
  opacity: 0.96;
}

body {
  border-radius: 16px;
  border: 3px #89b4fa solid;
  box-shadow: 2 9px 15px #232634;
}

body.has-dark {
  border-color: #89b4fa;
}

body:after {
  border: unset;
}

#bar {
  background: #1e1e2e;
  border-radius: unset;
  border-bottom: unset;
  height: 36px;
  padding: 9px 10px;
  padding-bottom: 5px;
}

.has-dark #bar {
  background: #1e1e2e;
}

#bar::before {
  content: "❯";
  display: inline-block;
  width: 1rem;
  height: 16px;
  position: absolute;
  left: 1rem;
  z-index: 300;
  font-size: 10;
  padding: 6px 0;
  line-height: 1.6em;
  text-align: right;
  color: #c6d0f5;
  font-weight: bold;
}

.has-dark #bar::before {
  color: #181825;
}

#input {
  border: none;
  background: none;
  box-shadow: unset;
  font-size: 20px;
  color: #cdd6f4;
  padding-left: 40rem;
}

.has-dark #input {
  color: #cdd6f4;
}

#toolbar {
  top: 7px;
  right: 14px;
}

#toolbar .button {
  height: 23px;
  width: 24px;
  padding: 3px;
  cursor: pointer;
  border: 3px transparent solid;
  position: relative;
  opacity: 0.5;
  transition: 100ms ease-in-out opacity;
}

#toolbar .button:hover {
  background: unset;
  opacity: 1;
}

#toolbar .button>svg {
  opacity: 0.5;
}

#toolbar .button#toggle-dark>svg {
  transform: translateY(1px) rotate(45deg);
}

#toolbar .button#close>svg {
  transform: scale(1.4);
}

#toolbar .button#toggle-dark .i-moon {
  fill: unset;
  stroke-width: 1.4;
}

#toolbar .button#toggle-dark .i-sun {
  stroke-width: 2.1;
}

.has-dark #toolbar .button#toggle-dark .i-moon {
  fill: #ddd8cd;
  stroke: #ddd8cd;
}

.has-dark #toolbar .button#toggle-dark .i-sun {
  fill: #ddd8cd;
  stroke: #ddd8cd;
}

.has-dark #toolbar .button#close>svg {
  fill: #ddd8cd;
  stroke: #ddd8cd;
}

#list {
  background: #181825;
  border-radius: unset;
  padding: 5px;
  padding-bottom: 6px;
}

.has-dark #list {
  background: #181825;
}

.item {
  padding: 6px 10px;
  padding-top: 3px;
  margin: 0 5px;
  margin-top: -2px;
  border-radius: 6px;
  border: unset;
  border: 3px transparent solid;
  height: 44px;
}

.item::before {
  position: absolute;
  background: none;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  content: "";
  z-index: -1;
}

.item.s,
.item:hover {
  background-color: unset;
  border: 3px #89b4fa solid;
}

.has-dark .item.s,
.has-dark .item:hover {
  border: 3px #89b4fa solid;
}

.item.s::before {
  background-color: rgba(255, 255, 255, 0.836);
}

.item:hover::before {
  background-color: #fff;
}

.has-dark .item.s::before {
  background-color: rgb(137, 180, 250, 0.2);
}

.has-dark .item:hover::before {
  background-color: rgb(137, 180, 250, 0.1);
}

.item .icon {
  width: 24px;
  height: 24px;
  padding-right: unset;
  margin-right: 10px;
  margin-top: 5px;
  background-position: bottom right;
}

.has-dark .item .icon {
  fill: #a5adce;
  stroke: #a5adce;
}

.item .icon path {
  opacity: 0.45;
  position: absolute;
  z-index: -1;
  transform-origin: 0px 0px;
  transform: scale(0.75);
}

.item .top {
  color: #cdd6f4;
  position: relative;
  height: 30px;
}

.has-dark .item .top {
  color: #cdd6f4;
}

.item .top .title {
  font-size: 16;
  line-height: 0.8em;
  margin-top: 2px;
}

.item .top .title match {
  color: #89dceb;
}

.has-dark .item .top .title match {
  color: #89dceb;
}

.item .top .title:empty::after {
  content: "<blank>";
}

.item .bottom {
  margin-top: -12px;
  padding-left: 14px;
}

.item .bottom a {
  color: #a5adce;
  opacity: 0.9;
  font-size: 16;
}

.has-dark .item .bottom a {
  color: #a5adce;
  opacity: 0.9;
}

.item .bottom a match {
  color: #89dceb;
}

.has-dark .item .bottom a match {
  color: #89dceb;
}

/* #find */
/* ^ do not touch this line ^ */

* {
  font-family: "JetBrainsMono Nerd Font" !important;
  background: unset;
}

:host,
body {
  background-color: #181825 !important;
  margin: 0 !important;
  padding: 0 !important;
}

:host(.D),
body.D {
  background-color: #181825 !important;
  color: #c6d0f5 !important;
}

.r {
  color: #c6d0f5;
  border: none;
  border-radius: unset;
  box-shadow: unset;
  background: #181825;
  height: 10px;
}

.r.D {
  background: #181825;
  color: #c6d0f5;
}

#i {
  color: #c6d0f5;
}

.D #i {
  color: #c6d0f5;
}
```
